"""Folders of a workspace output tree that keep the documents generated by each module.

Every generated document lives below ``output/reports/<module>/``. Workspaces,
backups and transfer packages written with the former layout (module folders
directly below ``output/`` and loose documents in ``output/reports/``) are moved
to these folders once, and the paths stored in the workspace database follow them.
"""
from __future__ import annotations

import re
import shutil
import sqlite3
from contextlib import closing
from pathlib import Path

REPORTS_FOLDER = 'reports'
DASHBOARDS_FOLDER = 'dashboards'
CDR_ANALYSIS_FOLDER = 'cdr-analysis'
NETWORK_INSIGHTS_FOLDER = 'network-insights'
REPORTS_OLD_FOLDER = 'reports-old'
REPORTS_CHARTS_OLD_FOLDER = 'reports-charts-old'
REPORTING_JOBS_FOLDER = 'reporting-jobs'
MODULE_FOLDERS = frozenset({
    DASHBOARDS_FOLDER, CDR_ANALYSIS_FOLDER, NETWORK_INSIGHTS_FOLDER,
    REPORTS_OLD_FOLDER, REPORTS_CHARTS_OLD_FOLDER, REPORTING_JOBS_FOLDER,
})
# Former folders directly below output/ and the module folder that replaces each one.
LEGACY_OUTPUT_FOLDERS = (
    ('dashboards', DASHBOARDS_FOLDER),
    ('reporting', REPORTING_JOBS_FOLDER),
    ('charts', REPORTS_CHARTS_OLD_FOLDER),
    ('report-charts', REPORTS_CHARTS_OLD_FOLDER),
)
STORED_PATH_COLUMNS = (
    ('dashboard_ppt_jobs', 'output_path'),
    ('generated_jobs', 'output_path'),
    ('report_task_runs', 'output_dir'),
)
NETWORK_INSIGHTS_FILE = re.compile(r'_summary_network_insights\.(?:pptx|docx)$')
CDR_ANALYSIS_FILE = re.compile(r'(?:_summary_dataset_analysis|_report(?:_[0-9a-f]{10})?)\.(?:pptx|docx)$')


def reports_root(output_dir: Path | str) -> Path:
    return Path(output_dir) / REPORTS_FOLDER


def module_output_dir(output_dir: Path | str, folder: str, *, create: bool = False) -> Path:
    """Return ``output/reports/<folder>`` of a workspace output tree."""
    directory = reports_root(output_dir) / folder
    if create:
        directory.mkdir(parents=True, exist_ok=True)
    return directory


def _loose_report_folder(item: Path) -> str:
    """Module folder of an entry left directly in output/reports by an earlier version."""
    if item.is_dir():
        return REPORTS_OLD_FOLDER
    if NETWORK_INSIGHTS_FILE.search(item.name):
        return NETWORK_INSIGHTS_FOLDER
    if CDR_ANALYSIS_FILE.search(item.name):
        return CDR_ANALYSIS_FOLDER
    return REPORTS_OLD_FOLDER


def _merge_into(source: Path, destination: Path, moves: list[tuple[Path, Path]]) -> None:
    """Move ``source`` to ``destination``, merging folders and never overwriting existing entries."""
    if not source.exists() or source == destination:
        return
    if not destination.exists():
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(source), str(destination))
        moves.append((source, destination))
        return
    if source.is_dir() and destination.is_dir():
        for child in list(source.iterdir()):
            _merge_into(child, destination / child.name, moves)
        try:
            source.rmdir()
        except OSError:
            pass


def _rewrite_stored_paths(database_path: Path, moves: list[tuple[Path, Path]]) -> None:
    if not Path(database_path).is_file():
        return
    prefixes = sorted(((str(old), str(new)) for old, new in moves), key=lambda item: len(item[0]), reverse=True)
    with closing(sqlite3.connect(database_path, timeout=60)) as connection, connection:
        tables = {str(row[0]) for row in connection.execute("SELECT name FROM sqlite_master WHERE type = 'table'")}
        for table, column in STORED_PATH_COLUMNS:
            if table not in tables:
                continue
            for row_id, value in connection.execute(f'SELECT rowid, {column} FROM {table}').fetchall():
                text = str(value or '')
                for old, new in prefixes:
                    if text == old or text.startswith(old + '/'):
                        connection.execute(f'UPDATE {table} SET {column} = ? WHERE rowid = ?', (new + text[len(old):], row_id))
                        break


def migrate_output_layout(output_dir: Path | str, database_path: Path | str) -> bool:
    """Move documents written with the former output layout into their module folders.

    Returns whether anything was moved. Safe to call on every workspace activation.
    """
    output_dir = Path(output_dir)
    root = reports_root(output_dir)
    moves: list[tuple[Path, Path]] = []
    for legacy, folder in LEGACY_OUTPUT_FOLDERS:
        _merge_into(output_dir / legacy, root / folder, moves)
    if root.is_dir():
        for item in list(root.iterdir()):
            if item.name in MODULE_FOLDERS or item.name.startswith('.'):
                continue
            _merge_into(item, root / _loose_report_folder(item) / item.name, moves)
    if moves:
        _rewrite_stored_paths(Path(database_path), moves)
    return bool(moves)
