"""Self-contained seed scoring configuration used by scoring tests."""
from __future__ import annotations

from copy import deepcopy

from src.modules.scoring_config import validate_scoring_configuration


_INITIAL_SCORING_CONFIGURATION = {'version': '2026Q2',
 'scope': {'environments': {'DriveCity': {'sheet': 'DriveCity',
                                          'g_level_1': 'Drive',
                                          'g_level_2': 'City',
                                          'total_points': 650.0,
                                          'weight_share': 0.65},
                            'DriveConnectionroad': {'sheet': 'DriveConnectionroad',
                                                    'g_level_1': 'Drive',
                                                    'g_level_2': 'Connectionroad',
                                                    'total_points': 350.0,
                                                    'weight_share': 0.35}},
           'environment_fields': ['G_Level_1', 'G_Level_2'],
           'environment_mapping': {'Drive + City': 'DriveCity',
                                   'Drive + Connectionroad': 'DriveConnectionroad'},
           'tableau_group_key': '[Operator] + "_" + [G_Level_1] + "_" + [G_Level_2]',
           'tableau_aggregate_group_by': ['dataset'],
           'campaign_in_tableau_group_key': False,
           'total_max_points': 1000.0,
           'allocation_note': 'The workbook allocates 650 points to DriveCity and 350 to '
                              'DriveConnectionroad.'},
 'interpolation': {'score_range': [0.0, 1.0],
                   'medium_score': 0.8,
                   'high_score_without_ultra': 1.0,
                   'high_score_with_ultra': 0.95,
                   'ultra_score': 1.0,
                   'method': 'piecewise_linear',
                   'clamp_to_range': True,
                   'source_note': 'The workbook assigns 80% at Medium and 95% at High when Ultra '
                                  'exists, except C25 and C30 which use 90%; High without Ultra '
                                  'and Ultra score 100%.'},
 'metrics': [{'code': 'C5',
              'category': 'CLASSIC CALLS',
              'kpi': 'CALL SUCCESS RATIO [%]',
              'source_kind': 'voice',
              'kpi_type': 'Reliable',
              'direction': 'higher_is_better',
              'calculation': {'source_kind': 'voice',
                              'formula': '100 * SUM(Call_Status == "Completed") / '
                                         'COUNT(Call_Status)',
                              'filters': {'Session_Type': ['CALL', 'MultiRAB CALL']},
                              'denominator': 'non-null Call_Status rows'},
              'contexts': {'DriveCity': {'max_points': 73.4825,
                                         'thresholds': {'low': 85.0,
                                                        'medium': 98.0,
                                                        'high': 100.0,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G4:J4',
                                         'weight_reference': 'DriveCity!F4'},
                           'DriveConnectionroad': {'max_points': 39.567499999999995,
                                                   'thresholds': {'low': 85.0,
                                                                  'medium': 98.0,
                                                                  'high': 100.0,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G4:J4',
                                                   'weight_reference': 'DriveConnectionroad!F4'}}},
             {'code': 'C6',
              'category': 'CLASSIC CALLS',
              'kpi': 'CALL SETUP TIME [s]',
              'source_kind': 'voice',
              'kpi_type': 'Diff',
              'direction': 'lower_is_better',
              'calculation': {'source_kind': 'voice',
                              'formula': 'AVG(Call_Setup_Time)',
                              'filters': {'Session_Type': ['CALL', 'MultiRAB CALL'],
                                          'Call_Status': ['Completed', 'Dropped']},
                              'denominator': 'non-null Call_Setup_Time rows'},
              'contexts': {'DriveCity': {'max_points': 8.645000000000001,
                                         'thresholds': {'low': 10.0,
                                                        'medium': 3.0,
                                                        'high': 1.5,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G5:J5',
                                         'weight_reference': 'DriveCity!F5'},
                           'DriveConnectionroad': {'max_points': 4.655,
                                                   'thresholds': {'low': 10.0,
                                                                  'medium': 3.0,
                                                                  'high': 1.5,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G5:J5',
                                                   'weight_reference': 'DriveConnectionroad!F5'}}},
             {'code': 'C7',
              'category': 'CLASSIC CALLS',
              'kpi': 'CALL SETUP TIME > 10 s [%]',
              'source_kind': 'voice',
              'kpi_type': 'Diff',
              'direction': 'lower_is_better',
              'calculation': {'source_kind': 'voice',
                              'formula': '100 * SUM(Call_Setup_Time > 10) / COUNT(Call_Status)',
                              'filters': {'Session_Type': ['CALL', 'MultiRAB CALL'],
                                          'Call_Status': ['Completed', 'Dropped']},
                              'denominator': 'non-null Call_Status rows'},
              'contexts': {'DriveCity': {'max_points': 4.322500000000001,
                                         'thresholds': {'low': 3.0,
                                                        'medium': 0.6,
                                                        'high': 0.0,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G6:J6',
                                         'weight_reference': 'DriveCity!F6'},
                           'DriveConnectionroad': {'max_points': 2.3275,
                                                   'thresholds': {'low': 3.0,
                                                                  'medium': 0.6,
                                                                  'high': 0.0,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G6:J6',
                                                   'weight_reference': 'DriveConnectionroad!F6'}}},
             {'code': 'C8',
              'category': 'CLASSIC CALLS',
              'kpi': 'POLQA < 1.6 [%]',
              'source_kind': 'speech',
              'kpi_type': 'Reliable',
              'direction': 'lower_is_better',
              'calculation': {'source_kind': 'speech',
                              'formula': '100 * SUM(LQ <= 1.6) / COUNT(Session_Type)',
                              'filters': {'Session_Type': ['CALL', 'MultiRAB CALL']},
                              'denominator': 'non-null Session_Type rows; condition is <= although '
                                             'label says <'},
              'contexts': {'DriveCity': {'max_points': 22.75,
                                         'thresholds': {'low': 10.0,
                                                        'medium': 0.5,
                                                        'high': 0.0,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G7:J7',
                                         'weight_reference': 'DriveCity!F7'},
                           'DriveConnectionroad': {'max_points': 12.25,
                                                   'thresholds': {'low': 10.0,
                                                                  'medium': 0.5,
                                                                  'high': 0.0,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G7:J7',
                                                   'weight_reference': 'DriveConnectionroad!F7'}}},
             {'code': 'C9',
              'category': 'CLASSIC CALLS',
              'kpi': 'POLQA [MOS',
              'source_kind': 'speech',
              'kpi_type': 'Diff',
              'direction': 'higher_is_better',
              'calculation': {'source_kind': 'speech',
                              'formula': 'AVG(LQ)',
                              'filters': {'Session_Type': ['CALL', 'MultiRAB CALL']},
                              'denominator': 'non-null LQ rows'},
              'contexts': {'DriveCity': {'max_points': 7.585500000000001,
                                         'thresholds': {'low': 2.0,
                                                        'medium': 3.8,
                                                        'high': 4.5,
                                                        'ultra': {'rule': 'fixed', 'value': 4.7}},
                                         'threshold_reference': 'DriveCity!G8:J8',
                                         'weight_reference': 'DriveCity!F8'},
                           'DriveConnectionroad': {'max_points': 4.084499999999999,
                                                   'thresholds': {'low': 2.0,
                                                                  'medium': 3.8,
                                                                  'high': 4.5,
                                                                  'ultra': {'rule': 'fixed',
                                                                            'value': 4.7}},
                                                   'threshold_reference': 'DriveConnectionroad!G8:J8',
                                                   'weight_reference': 'DriveConnectionroad!F8'}}},
             {'code': 'C10',
              'category': 'CLASSIC CALLS',
              'kpi': 'DISTURBED & IMPAIRED CALL [%]',
              'source_kind': 'voice',
              'kpi_type': 'Diff',
              'direction': 'lower_is_better',
              'calculation': {'source_kind': 'voice',
                              'formula': '100 * SUM(Call_Status == "Completed" AND '
                                         'Disturbed_and_Impaired_Call == "Yes") / '
                                         'COUNT(Call_Status)',
                              'filters': {'Session_Type': ['CALL', 'MultiRAB CALL']},
                              'denominator': 'non-null Call_Status rows'},
              'contexts': {'DriveCity': {'max_points': 15.164499999999999,
                                         'thresholds': {'low': 10.0,
                                                        'medium': 0.5,
                                                        'high': 0.0,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G9:J9',
                                         'weight_reference': 'DriveCity!F9'},
                           'DriveConnectionroad': {'max_points': 8.1655,
                                                   'thresholds': {'low': 10.0,
                                                                  'medium': 0.5,
                                                                  'high': 0.0,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G9:J9',
                                                   'weight_reference': 'DriveConnectionroad!F9'}}},
             {'code': 'C11',
              'category': 'WHATSAPP CALLS',
              'kpi': 'CALL SUCCESS RATIO [%]',
              'source_kind': 'voice',
              'kpi_type': 'Reliable',
              'direction': 'higher_is_better',
              'calculation': {'source_kind': 'voice',
                              'formula': '100 * SUM(Call_Status == "Completed") / '
                                         'COUNT(Call_Status)',
                              'filters': {'Session_Type': ['WhatsApp CALL']},
                              'denominator': 'non-null Call_Status rows'},
              'contexts': {'DriveCity': {'max_points': 56.875,
                                         'thresholds': {'low': 85.0,
                                                        'medium': 98.0,
                                                        'high': 100.0,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G10:J10',
                                         'weight_reference': 'DriveCity!F10'},
                           'DriveConnectionroad': {'max_points': 30.624999999999996,
                                                   'thresholds': {'low': 85.0,
                                                                  'medium': 98.0,
                                                                  'high': 100.0,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G10:J10',
                                                   'weight_reference': 'DriveConnectionroad!F10'}}},
             {'code': 'C12',
              'category': 'WHATSAPP CALLS',
              'kpi': 'POLQA < 1.6 [%]',
              'source_kind': 'speech',
              'kpi_type': 'Reliable',
              'direction': 'lower_is_better',
              'calculation': {'source_kind': 'speech',
                              'formula': '100 * SUM(LQ <= 1.6) / COUNT(Session_Type)',
                              'filters': {'Session_Type': ['WhatsApp CALL']},
                              'denominator': 'non-null Session_Type rows; condition is <= although '
                                             'label says <'},
              'contexts': {'DriveCity': {'max_points': 14.7875,
                                         'thresholds': {'low': 10.0,
                                                        'medium': 1.0,
                                                        'high': 0.0,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G11:J11',
                                         'weight_reference': 'DriveCity!F11'},
                           'DriveConnectionroad': {'max_points': 7.9624999999999995,
                                                   'thresholds': {'low': 10.0,
                                                                  'medium': 1.0,
                                                                  'high': 0.0,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G11:J11',
                                                   'weight_reference': 'DriveConnectionroad!F11'}}},
             {'code': 'C13',
              'category': 'WHATSAPP CALLS',
              'kpi': 'POLQA [MOS]',
              'source_kind': 'speech',
              'kpi_type': 'Diff',
              'direction': 'higher_is_better',
              'calculation': {'source_kind': 'speech',
                              'formula': 'AVG(LQ)',
                              'filters': {'Session_Type': ['WhatsApp CALL']},
                              'denominator': 'non-null LQ rows'},
              'contexts': {'DriveCity': {'max_points': 4.9270000000000005,
                                         'thresholds': {'low': 2.0,
                                                        'medium': 3.8,
                                                        'high': 4.5,
                                                        'ultra': {'rule': 'fixed', 'value': 4.7}},
                                         'threshold_reference': 'DriveCity!G12:J12',
                                         'weight_reference': 'DriveCity!F12'},
                           'DriveConnectionroad': {'max_points': 2.653,
                                                   'thresholds': {'low': 2.0,
                                                                  'medium': 3.8,
                                                                  'high': 4.5,
                                                                  'ultra': {'rule': 'fixed',
                                                                            'value': 4.7}},
                                                   'threshold_reference': 'DriveConnectionroad!G12:J12',
                                                   'weight_reference': 'DriveConnectionroad!F12'}}},
             {'code': 'C14',
              'category': 'WHATSAPP CALLS',
              'kpi': 'DISTURBED & IMPAIRED CALL [%]',
              'source_kind': 'voice',
              'kpi_type': 'Diff',
              'direction': 'lower_is_better',
              'calculation': {'source_kind': 'voice',
                              'formula': '100 * SUM(Call_Status == "Completed" AND '
                                         'Disturbed_and_Impaired_Call == "Yes") / '
                                         'COUNT(Call_Status)',
                              'filters': {'Session_Type': ['WhatsApp CALL']},
                              'denominator': 'non-null Call_Status rows'},
              'contexts': {'DriveCity': {'max_points': 9.8605,
                                         'thresholds': {'low': 10.0,
                                                        'medium': 0.5,
                                                        'high': 0.0,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G13:J13',
                                         'weight_reference': 'DriveCity!F13'},
                           'DriveConnectionroad': {'max_points': 5.3095,
                                                   'thresholds': {'low': 10.0,
                                                                  'medium': 0.5,
                                                                  'high': 0.0,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G13:J13',
                                                   'weight_reference': 'DriveConnectionroad!F13'}}},
             {'code': 'C15',
              'category': 'MULTI RAB',
              'kpi': 'MULTI RAB DATA TRANSFER SUCCESS RATIO [%]',
              'source_kind': 'voice',
              'kpi_type': 'Diff',
              'direction': 'higher_is_better',
              'calculation': {'source_kind': 'voice',
                              'formula': '100 * SUM(Test_Status == "Successful") / '
                                         'COUNT(Call_Status)',
                              'filters': {'Session_Type': ['MultiRAB CALL']},
                              'denominator': 'non-null Call_Status rows'},
              'contexts': {'DriveCity': {'max_points': 9.1,
                                         'thresholds': {'low': 80.0,
                                                        'medium': 98.5,
                                                        'high': 100.0,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G14:J14',
                                         'weight_reference': 'DriveCity!F14'},
                           'DriveConnectionroad': {'max_points': 4.8999999999999995,
                                                   'thresholds': {'low': 80.0,
                                                                  'medium': 98.5,
                                                                  'high': 100.0,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G14:J14',
                                                   'weight_reference': 'DriveConnectionroad!F14'}}},
             {'code': 'C17',
              'category': 'TRANSFER',
              'kpi': 'FDFS DL SUCCESS RATIO [%]',
              'source_kind': 'data',
              'kpi_type': 'Reliable',
              'direction': 'higher_is_better',
              'calculation': {'source_kind': 'data',
                              'formula': '100 * SUM(CONTAINS(Test_Result, "Completed")) / '
                                         'COUNT(Test_Result)',
                              'filters': {'Test_Name contains': ['FDFS', 'DL']},
                              'denominator': 'non-null Test_Result rows'},
              'contexts': {'DriveCity': {'max_points': 30.419999999999998,
                                         'thresholds': {'low': 80.0,
                                                        'medium': 98.5,
                                                        'high': 100.0,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G15:J15',
                                         'weight_reference': 'DriveCity!F15'},
                           'DriveConnectionroad': {'max_points': 16.38,
                                                   'thresholds': {'low': 80.0,
                                                                  'medium': 98.5,
                                                                  'high': 100.0,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G15:J15',
                                                   'weight_reference': 'DriveConnectionroad!F15'}}},
             {'code': 'C18',
              'category': 'TRANSFER',
              'kpi': 'FDFS DL TRANSFER TIME [s]',
              'source_kind': 'data',
              'kpi_type': 'Diff',
              'direction': 'lower_is_better',
              'calculation': {'source_kind': 'data',
                              'formula': 'AVG(Transfer_Duration)',
                              'filters': {'Test_Name contains': ['FDFS', 'DL'],
                                          'Test_Result': 'contains Completed'},
                              'denominator': 'non-null Transfer_Duration rows'},
              'contexts': {'DriveCity': {'max_points': 20.28,
                                         'thresholds': {'low': 6.0,
                                                        'medium': 4.0,
                                                        'high': 1.5,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G16:J16',
                                         'weight_reference': 'DriveCity!F16'},
                           'DriveConnectionroad': {'max_points': 10.92,
                                                   'thresholds': {'low': 6.0,
                                                                  'medium': 4.0,
                                                                  'high': 1.5,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G16:J16',
                                                   'weight_reference': 'DriveConnectionroad!F16'}}},
             {'code': 'C19',
              'category': 'TRANSFER',
              'kpi': 'FDFS UL SUCCESS RATIO [%]',
              'source_kind': 'data',
              'kpi_type': 'Reliable',
              'direction': 'higher_is_better',
              'calculation': {'source_kind': 'data',
                              'formula': '100 * SUM(CONTAINS(Test_Result, "Completed")) / '
                                         'COUNT(Test_Result)',
                              'filters': {'Test_Name contains': ['FDFS', 'UL']},
                              'denominator': 'non-null Test_Result rows'},
              'contexts': {'DriveCity': {'max_points': 15.209999999999999,
                                         'thresholds': {'low': 80.0,
                                                        'medium': 98.5,
                                                        'high': 100.0,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G17:J17',
                                         'weight_reference': 'DriveCity!F17'},
                           'DriveConnectionroad': {'max_points': 8.19,
                                                   'thresholds': {'low': 80.0,
                                                                  'medium': 98.5,
                                                                  'high': 100.0,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G17:J17',
                                                   'weight_reference': 'DriveConnectionroad!F17'}}},
             {'code': 'C20',
              'category': 'TRANSFER',
              'kpi': 'FDFS UL TRANSFER TIME [s]',
              'source_kind': 'data',
              'kpi_type': 'Diff',
              'direction': 'lower_is_better',
              'calculation': {'source_kind': 'data',
                              'formula': 'AVG(Transfer_Duration)',
                              'filters': {'Test_Name contains': ['FDFS', 'UL'],
                                          'Test_Result': 'contains Completed'},
                              'denominator': 'non-null Transfer_Duration rows'},
              'contexts': {'DriveCity': {'max_points': 10.14,
                                         'thresholds': {'low': 6.0,
                                                        'medium': 4.0,
                                                        'high': 1.5,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G18:J18',
                                         'weight_reference': 'DriveCity!F18'},
                           'DriveConnectionroad': {'max_points': 5.46,
                                                   'thresholds': {'low': 6.0,
                                                                  'medium': 4.0,
                                                                  'high': 1.5,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G18:J18',
                                                   'weight_reference': 'DriveConnectionroad!F18'}}},
             {'code': 'C21',
              'category': 'TRANSFER',
              'kpi': 'FDTT DL THROUGHPUT > 2Mbit/s [%]',
              'source_kind': 'data',
              'kpi_type': 'Reliable',
              'direction': 'higher_is_better',
              'calculation': {'source_kind': 'data',
                              'formula': '100 * COUNT(Mean_Data_Rate > 2) / COUNT(Mean_Data_Rate)',
                              'filters': {'Test_Name contains': ['FDTT', 'DL'],
                                          'Test_Result': 'contains Completed'},
                              'denominator': 'non-null Mean_Data_Rate rows'},
              'contexts': {'DriveCity': {'max_points': 20.28,
                                         'thresholds': {'low': 95.0,
                                                        'medium': 98.5,
                                                        'high': 100.0,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G19:J19',
                                         'weight_reference': 'DriveCity!F19'},
                           'DriveConnectionroad': {'max_points': 10.92,
                                                   'thresholds': {'low': 95.0,
                                                                  'medium': 98.5,
                                                                  'high': 100.0,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G19:J19',
                                                   'weight_reference': 'DriveConnectionroad!F19'}}},
             {'code': 'C22',
              'category': 'TRANSFER',
              'kpi': 'FDTT DL THROUGHPUT > 5Mbit/s [%]',
              'source_kind': 'data',
              'kpi_type': 'Diff',
              'direction': 'higher_is_better',
              'calculation': {'source_kind': 'data',
                              'formula': '100 * COUNT(Mean_Data_Rate > 5) / COUNT(Mean_Data_Rate)',
                              'filters': {'Test_Name contains': ['FDTT', 'DL'],
                                          'Test_Result': 'contains Completed'},
                              'denominator': 'non-null Mean_Data_Rate rows'},
              'contexts': {'DriveCity': {'max_points': 25.35,
                                         'thresholds': {'low': 90.0,
                                                        'medium': 95.0,
                                                        'high': 100.0,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G20:J20',
                                         'weight_reference': 'DriveCity!F20'},
                           'DriveConnectionroad': {'max_points': 13.649999999999999,
                                                   'thresholds': {'low': 90.0,
                                                                  'medium': 95.0,
                                                                  'high': 100.0,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G20:J20',
                                                   'weight_reference': 'DriveConnectionroad!F20'}}},
             {'code': 'C23',
              'category': 'TRANSFER',
              'kpi': 'FDTT DL THROUGHPUT > 20Mbit/s [%]',
              'source_kind': 'data',
              'kpi_type': 'Diff',
              'direction': 'higher_is_better',
              'calculation': {'source_kind': 'data',
                              'formula': '100 * COUNT(Mean_Data_Rate > 20) / COUNT(Mean_Data_Rate)',
                              'filters': {'Test_Name contains': ['FDTT', 'DL'],
                                          'Test_Result': 'contains Completed'},
                              'denominator': 'non-null Mean_Data_Rate rows'},
              'contexts': {'DriveCity': {'max_points': 25.35,
                                         'thresholds': {'low': 0.0,
                                                        'medium': 90.0,
                                                        'high': 100.0,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G21:J21',
                                         'weight_reference': 'DriveCity!F21'},
                           'DriveConnectionroad': {'max_points': 13.649999999999999,
                                                   'thresholds': {'low': 0.0,
                                                                  'medium': 90.0,
                                                                  'high': 100.0,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G21:J21',
                                                   'weight_reference': 'DriveConnectionroad!F21'}}},
             {'code': 'C24',
              'category': 'TRANSFER',
              'kpi': 'FDTT DL THROUGHPUT > 100Mbit/s [%]',
              'source_kind': 'data',
              'kpi_type': 'Diff',
              'direction': 'higher_is_better',
              'calculation': {'source_kind': 'data',
                              'formula': '100 * COUNT(Mean_Data_Rate > 100) / '
                                         'COUNT(Mean_Data_Rate)',
                              'filters': {'Test_Name contains': ['FDTT', 'DL'],
                                          'Test_Result': 'contains Completed'},
                              'denominator': 'non-null Mean_Data_Rate rows'},
              'contexts': {'DriveCity': {'max_points': 15.209999999999999,
                                         'thresholds': {'low': 0.0,
                                                        'medium': 50.0,
                                                        'high': 100.0,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G22:J22',
                                         'weight_reference': 'DriveCity!F22'},
                           'DriveConnectionroad': {'max_points': 8.19,
                                                   'thresholds': {'low': 0.0,
                                                                  'medium': 50.0,
                                                                  'high': 100.0,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G22:J22',
                                                   'weight_reference': 'DriveConnectionroad!F22'}}},
             {'code': 'C25',
              'category': 'TRANSFER',
              'kpi': 'FDTT DL THROUGHPUT P90 [Mbit/s]',
              'source_kind': 'data',
              'kpi_type': 'Diff',
              'direction': 'higher_is_better',
              'calculation': {'source_kind': 'data',
                              'formula': 'PCT90(Mean_Data_Rate)',
                              'filters': {'Test_Name contains': ['FDTT', 'DL'],
                                          'Test_Result': 'contains Completed'},
                              'denominator': 'non-null Mean_Data_Rate rows'},
              'contexts': {'DriveCity': {'max_points': 15.209999999999999,
                                         'thresholds': {'low': 0.0,
                                                        'medium': 300.0,
                                                        'high': 500.0,
                                                        'ultra': {'rule': 'best_max',
                                                                  'source_formula': '=MAX(M23:O23)'}},
                                         'threshold_reference': 'DriveCity!G23:J23',
                                         'weight_reference': 'DriveCity!F23',
                                         'score_mapping': {'low_score': 0.0,
                                                           'medium_score': 0.8,
                                                           'high_score': 0.9,
                                                           'ultra_score': 1.0}},
                           'DriveConnectionroad': {'max_points': 8.19,
                                                   'thresholds': {'low': 0.0,
                                                                  'medium': 300.0,
                                                                  'high': 500.0,
                                                                  'ultra': {'rule': 'best_max',
                                                                            'source_formula': '=MAX(K23:O23)'}},
                                                   'threshold_reference': 'DriveConnectionroad!G23:J23',
                                                   'weight_reference': 'DriveConnectionroad!F23',
                                                   'score_mapping': {'low_score': 0.0,
                                                                     'medium_score': 0.8,
                                                                     'high_score': 0.9,
                                                                     'ultra_score': 1.0}}}},
             {'code': 'C26',
              'category': 'TRANSFER',
              'kpi': 'FDTT UL THROUGHPUT > 1Mbit/s [%]',
              'source_kind': 'data',
              'kpi_type': 'Reliable',
              'direction': 'higher_is_better',
              'calculation': {'source_kind': 'data',
                              'formula': '100 * COUNT(Mean_Data_Rate > 1) / COUNT(Mean_Data_Rate)',
                              'filters': {'Test_Name contains': ['UDP'],
                                          'Test_Result': 'contains Completed'},
                              'denominator': 'non-null Mean_Data_Rate rows'},
              'contexts': {'DriveCity': {'max_points': 10.14,
                                         'thresholds': {'low': 95.0,
                                                        'medium': 98.5,
                                                        'high': 100.0,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G24:J24',
                                         'weight_reference': 'DriveCity!F24'},
                           'DriveConnectionroad': {'max_points': 5.46,
                                                   'thresholds': {'low': 95.0,
                                                                  'medium': 98.5,
                                                                  'high': 100.0,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G24:J24',
                                                   'weight_reference': 'DriveConnectionroad!F24'}}},
             {'code': 'C27',
              'category': 'TRANSFER',
              'kpi': 'FDTT UL THROUGHPUT > 3Mbit/s [%]',
              'source_kind': 'data',
              'kpi_type': 'Diff',
              'direction': 'higher_is_better',
              'calculation': {'source_kind': 'data',
                              'formula': '100 * COUNT(Mean_Data_Rate > 3) / COUNT(Mean_Data_Rate)',
                              'filters': {'Test_Name contains': ['UDP'],
                                          'Test_Result': 'contains Completed'},
                              'denominator': 'non-null Mean_Data_Rate rows'},
              'contexts': {'DriveCity': {'max_points': 12.675,
                                         'thresholds': {'low': 90.0,
                                                        'medium': 95.0,
                                                        'high': 100.0,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G25:J25',
                                         'weight_reference': 'DriveCity!F25'},
                           'DriveConnectionroad': {'max_points': 6.824999999999999,
                                                   'thresholds': {'low': 90.0,
                                                                  'medium': 95.0,
                                                                  'high': 100.0,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G25:J25',
                                                   'weight_reference': 'DriveConnectionroad!F25'}}},
             {'code': 'C28',
              'category': 'TRANSFER',
              'kpi': 'FDTT UL THROUGHPUT > 10Mbit/s [%]',
              'source_kind': 'data',
              'kpi_type': 'Diff',
              'direction': 'higher_is_better',
              'calculation': {'source_kind': 'data',
                              'formula': '100 * COUNT(Mean_Data_Rate > 10) / COUNT(Mean_Data_Rate)',
                              'filters': {'Test_Name contains': ['UDP'],
                                          'Test_Result': 'contains Completed'},
                              'denominator': 'non-null Mean_Data_Rate rows'},
              'contexts': {'DriveCity': {'max_points': 12.675,
                                         'thresholds': {'low': 0.0,
                                                        'medium': 90.0,
                                                        'high': 100.0,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G26:J26',
                                         'weight_reference': 'DriveCity!F26'},
                           'DriveConnectionroad': {'max_points': 6.824999999999999,
                                                   'thresholds': {'low': 0.0,
                                                                  'medium': 90.0,
                                                                  'high': 100.0,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G26:J26',
                                                   'weight_reference': 'DriveConnectionroad!F26'}}},
             {'code': 'C29',
              'category': 'TRANSFER',
              'kpi': 'FDTT UL THROUGHPUT > 20Mbit/s [%]',
              'source_kind': 'data',
              'kpi_type': 'Diff',
              'direction': 'higher_is_better',
              'calculation': {'source_kind': 'data',
                              'formula': '100 * COUNT(Mean_Data_Rate > 20) / COUNT(Mean_Data_Rate)',
                              'filters': {'Test_Name contains': ['UDP'],
                                          'Test_Result': 'contains Completed'},
                              'denominator': 'non-null Mean_Data_Rate rows'},
              'contexts': {'DriveCity': {'max_points': 7.6049999999999995,
                                         'thresholds': {'low': 0.0,
                                                        'medium': 50.0,
                                                        'high': 100.0,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G27:J27',
                                         'weight_reference': 'DriveCity!F27'},
                           'DriveConnectionroad': {'max_points': 4.095,
                                                   'thresholds': {'low': 0.0,
                                                                  'medium': 50.0,
                                                                  'high': 100.0,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G27:J27',
                                                   'weight_reference': 'DriveConnectionroad!F27'}}},
             {'code': 'C30',
              'category': 'TRANSFER',
              'kpi': 'FDTT UL THROUGHPUT P90 [Mbit/s]',
              'source_kind': 'data',
              'kpi_type': 'Diff',
              'direction': 'higher_is_better',
              'calculation': {'source_kind': 'data',
                              'formula': 'PCT90(Mean_Data_Rate)',
                              'filters': {'Test_Name contains': ['UDP'],
                                          'Test_Result': 'contains Completed'},
                              'denominator': 'non-null Mean_Data_Rate rows'},
              'contexts': {'DriveCity': {'max_points': 7.6049999999999995,
                                         'thresholds': {'low': 0.0,
                                                        'medium': 50.0,
                                                        'high': 100.0,
                                                        'ultra': {'rule': 'best_max',
                                                                  'source_formula': '=MAX(M28:O28)'}},
                                         'threshold_reference': 'DriveCity!G28:J28',
                                         'weight_reference': 'DriveCity!F28',
                                         'score_mapping': {'low_score': 0.0,
                                                           'medium_score': 0.8,
                                                           'high_score': 0.9,
                                                           'ultra_score': 1.0}},
                           'DriveConnectionroad': {'max_points': 4.095,
                                                   'thresholds': {'low': 0.0,
                                                                  'medium': 50.0,
                                                                  'high': 100.0,
                                                                  'ultra': {'rule': 'best_max',
                                                                            'source_formula': '=MAX(K28:O28)'}},
                                                   'threshold_reference': 'DriveConnectionroad!G28:J28',
                                                   'weight_reference': 'DriveConnectionroad!F28',
                                                   'score_mapping': {'low_score': 0.0,
                                                                     'medium_score': 0.8,
                                                                     'high_score': 0.9,
                                                                     'ultra_score': 1.0}}}},
             {'code': 'C31',
              'category': 'HTTP/HTTPS BROWSING',
              'kpi': 'BROWSING TIME TO 1MB [ms]',
              'source_kind': 'data',
              'kpi_type': 'Diff',
              'direction': 'lower_is_better',
              'calculation': {'source_kind': 'data',
                              'formula': 'AVG(http_Browser_1MB_Reached_Duration)',
                              'filters': {'Type_of_Test': ['httpBrowser'],
                                          'http_Browser_Transferred_Bytes': '>= 1000000'},
                              'denominator': 'non-null duration rows after transferred-bytes '
                                             'filter'},
              'contexts': {'DriveCity': {'max_points': 33.800000000000004,
                                         'thresholds': {'low': 3000.0,
                                                        'medium': 2500.0,
                                                        'high': 1800.0,
                                                        'ultra': {'rule': 'best_min',
                                                                  'source_formula': '=MIN(M29:O29)'}},
                                         'threshold_reference': 'DriveCity!G29:J29',
                                         'weight_reference': 'DriveCity!F29'},
                           'DriveConnectionroad': {'max_points': 18.2,
                                                   'thresholds': {'low': 3000.0,
                                                                  'medium': 2500.0,
                                                                  'high': 1800.0,
                                                                  'ultra': {'rule': 'best_min',
                                                                            'source_formula': '=MIN(K29:O29)'}},
                                                   'threshold_reference': 'DriveConnectionroad!G29:J29',
                                                   'weight_reference': 'DriveConnectionroad!F29'}}},
             {'code': 'C32',
              'category': 'HTTP/HTTPS BROWSING',
              'kpi': 'BROWSING SUCCESS RATIO [%]',
              'source_kind': 'data',
              'kpi_type': 'Reliable',
              'direction': 'higher_is_better',
              'calculation': {'source_kind': 'data',
                              'formula': '100 * SUM(CONTAINS(Test_Result, "Completed")) / '
                                         'COUNT(Test_Result)',
                              'filters': {'Type_of_Test': ['httpBrowser']},
                              'denominator': 'non-null Test_Result rows'},
              'contexts': {'DriveCity': {'max_points': 50.7,
                                         'thresholds': {'low': 80.0,
                                                        'medium': 98.5,
                                                        'high': 100.0,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G30:J30',
                                         'weight_reference': 'DriveCity!F30'},
                           'DriveConnectionroad': {'max_points': 27.299999999999997,
                                                   'thresholds': {'low': 80.0,
                                                                  'medium': 98.5,
                                                                  'high': 100.0,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G30:J30',
                                                   'weight_reference': 'DriveConnectionroad!F30'}}},
             {'code': 'C33',
              'category': 'VIDEO STREAM',
              'kpi': 'VIDEO STREAMING SUCCESS RATIO [%]',
              'source_kind': 'data',
              'kpi_type': 'Reliable',
              'direction': 'higher_is_better',
              'calculation': {'source_kind': 'data',
                              'formula': '100 * SUM(CONTAINS(Test_Result, "Completed")) / '
                                         'COUNT(Test_Result)',
                              'filters': {'Type_of_Test': ['VideoStreaming']},
                              'denominator': 'non-null Test_Result rows'},
              'contexts': {'DriveCity': {'max_points': 54.080000000000005,
                                         'thresholds': {'low': 80.0,
                                                        'medium': 98.5,
                                                        'high': 100.0,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G31:J31',
                                         'weight_reference': 'DriveCity!F31'},
                           'DriveConnectionroad': {'max_points': 29.119999999999997,
                                                   'thresholds': {'low': 80.0,
                                                                  'medium': 98.5,
                                                                  'high': 100.0,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G31:J31',
                                                   'weight_reference': 'DriveConnectionroad!F31'}}},
             {'code': 'C34',
              'category': 'VIDEO STREAM',
              'kpi': 'VIDEO STREAMING TTFP >= 10 s [%]',
              'source_kind': 'data',
              'kpi_type': 'Diff',
              'direction': 'lower_is_better',
              'calculation': {'source_kind': 'data',
                              'formula': '100 * SUM(VideoStream_Time_to_First_Picture >= 10) / '
                                         'COUNT(Test_Result)',
                              'filters': {'Type_of_Test': ['VideoStreaming']},
                              'denominator': 'non-null Test_Result rows'},
              'contexts': {'DriveCity': {'max_points': 3.3800000000000003,
                                         'thresholds': {'low': 5.0,
                                                        'medium': 0.5,
                                                        'high': 0.0,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G32:J32',
                                         'weight_reference': 'DriveCity!F32'},
                           'DriveConnectionroad': {'max_points': 1.8199999999999998,
                                                   'thresholds': {'low': 5.0,
                                                                  'medium': 0.5,
                                                                  'high': 0.0,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G32:J32',
                                                   'weight_reference': 'DriveConnectionroad!F32'}}},
             {'code': 'C35',
              'category': 'VIDEO STREAM',
              'kpi': 'VIDEO STREAMING IRRITATING EXPERIENCE [%]',
              'source_kind': 'data',
              'kpi_type': 'Diff',
              'direction': 'lower_is_better',
              'calculation': {'source_kind': 'data',
                              'formula': '100 * SUM(Irritating_Video_Playout IS NOT NULL) / '
                                         'COUNT(Test_Result)',
                              'filters': {'Type_of_Test': ['VideoStreaming']},
                              'denominator': 'non-null Test_Result rows'},
              'contexts': {'DriveCity': {'max_points': 27.040000000000003,
                                         'thresholds': {'low': 10.0,
                                                        'medium': 2.5,
                                                        'high': 0.0,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G33:J33',
                                         'weight_reference': 'DriveCity!F33'},
                           'DriveConnectionroad': {'max_points': 14.559999999999999,
                                                   'thresholds': {'low': 10.0,
                                                                  'medium': 2.5,
                                                                  'high': 0.0,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G33:J33',
                                                   'weight_reference': 'DriveConnectionroad!F33'}}},
             {'code': 'C36',
              'category': 'INTERACTIVITY',
              'kpi': 'INTERACTIVITY PACKET ERROR RATIO [%]',
              'source_kind': 'data',
              'kpi_type': 'Diff',
              'direction': 'lower_is_better',
              'calculation': {'source_kind': 'data',
                              'formula': '100 * SUM(totalpacketlost) / SUM(Packets_Sent)',
                              'filters': {'Type_of_Test': ['Interactivity']},
                              'totalpacketlost': 'IFNULL(Packets_Lost,0) + '
                                                 'IFNULL(Packets_Discarded,0) + '
                                                 'IFNULL(INT(Packets_Corrupted),0) + '
                                                 'IFNULL(Packets_Not_Sent,0)',
                              'denominator': 'sum of Packets_Sent'},
              'contexts': {'DriveCity': {'max_points': 5.07,
                                         'thresholds': {'low': 10.0,
                                                        'medium': 5.0,
                                                        'high': 1.0,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G34:J34',
                                         'weight_reference': 'DriveCity!F34'},
                           'DriveConnectionroad': {'max_points': 2.73,
                                                   'thresholds': {'low': 10.0,
                                                                  'medium': 5.0,
                                                                  'high': 1.0,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G34:J34',
                                                   'weight_reference': 'DriveConnectionroad!F34'}}},
             {'code': 'C37',
              'category': 'INTERACTIVITY',
              'kpi': 'INTERACTIVITY MEDIAN RTT [MS]',
              'source_kind': 'data',
              'kpi_type': 'Diff',
              'direction': 'lower_is_better',
              'calculation': {'source_kind': 'data',
                              'formula': 'MEDIAN(Interactivity_RTT_Median)',
                              'filters': {'Type_of_Test': ['Interactivity']},
                              'denominator': 'non-null Interactivity_RTT_Median rows'},
              'contexts': {'DriveCity': {'max_points': 20.28,
                                         'thresholds': {'low': 60.0,
                                                        'medium': 45.0,
                                                        'high': 25.0,
                                                        'ultra': None},
                                         'threshold_reference': 'DriveCity!G35:J35',
                                         'weight_reference': 'DriveCity!F35'},
                           'DriveConnectionroad': {'max_points': 10.92,
                                                   'thresholds': {'low': 60.0,
                                                                  'medium': 45.0,
                                                                  'high': 25.0,
                                                                  'ultra': None},
                                                   'threshold_reference': 'DriveConnectionroad!G35:J35',
                                                   'weight_reference': 'DriveConnectionroad!F35'}}}],
 'validation_examples': {'mapping_workbook_sample': {'environment': 'DriveCity',
                                                     'kpi': 'CALL SUCCESS RATIO [%]',
                                                     'operator': 'O2 (UK)',
                                                     'measured_value': 98.86327755,
                                                     'expected_score': 0.8863277550000007,
                                                     'max_points': 73.4825,
                                                     'expected_weighted_points': 65.12957925678755},
                         'mapping_workbook_samples': [{'environment': 'DriveCity',
                                                       'kpi_code': 'C5',
                                                       'kpi': 'CALL SUCCESS RATIO [%]',
                                                       'operator': 'O2 (UK)',
                                                       'measured_value': 98.86327755,
                                                       'score_range_label': 'medium',
                                                       'expected_score_fraction': 0.8863277550000007,
                                                       'max_points': 73.4825,
                                                       'expected_weighted_points': 65.12957925678755,
                                                       'thresholds': {'low': 85.0,
                                                                      'medium': 98.0,
                                                                      'high': 100.0,
                                                                      'ultra': None},
                                                       'dynamic_ultra_threshold': None},
                                                      {'environment': 'DriveConnectionroad',
                                                       'kpi_code': 'C5',
                                                       'kpi': 'CALL SUCCESS RATIO [%]',
                                                       'operator': 'O2 (UK)',
                                                       'measured_value': 97.299903568,
                                                       'score_range_label': 'low',
                                                       'expected_score_fraction': 0.7569171426461542,
                                                       'max_points': 39.567499999999995,
                                                       'expected_weighted_points': 29.9493190416517,
                                                       'thresholds': {'low': 85.0,
                                                                      'medium': 98.0,
                                                                      'high': 100.0,
                                                                      'ultra': None},
                                                       'dynamic_ultra_threshold': None},
                                                      {'environment': 'DriveCity',
                                                       'kpi_code': 'C9',
                                                       'kpi': 'POLQA [MOS',
                                                       'operator': 'EE',
                                                       'measured_value': 4.681121578,
                                                       'score_range_label': 'high',
                                                       'expected_score_fraction': 0.9952803944999999,
                                                       'max_points': 7.585500000000001,
                                                       'expected_weighted_points': 7.54969943247975,
                                                       'thresholds': {'low': 2.0,
                                                                      'medium': 3.8,
                                                                      'high': 4.5,
                                                                      'ultra': {'rule': 'fixed',
                                                                                'value': 4.7}},
                                                       'dynamic_ultra_threshold': 4.7},
                                                      {'environment': 'DriveCity',
                                                       'kpi_code': 'C25',
                                                       'kpi': 'FDTT DL THROUGHPUT P90 [Mbit/s]',
                                                       'operator': '3',
                                                       'measured_value': 621.562,
                                                       'score_range_label': 'max',
                                                       'expected_score_fraction': 1,
                                                       'max_points': 15.209999999999999,
                                                       'expected_weighted_points': 15.209999999999999,
                                                       'thresholds': {'low': 0.0,
                                                                      'medium': 300.0,
                                                                      'high': 500.0,
                                                                      'ultra': {'rule': 'best_max',
                                                                                'source_formula': '=MAX(M23:O23)'}},
                                                       'dynamic_ultra_threshold': 478.212},
                                                      {'environment': 'DriveConnectionroad',
                                                       'kpi_code': 'C25',
                                                       'kpi': 'FDTT DL THROUGHPUT P90 [Mbit/s]',
                                                       'operator': '3',
                                                       'measured_value': 435.98,
                                                       'score_range_label': 'medium',
                                                       'expected_score_fraction': 0.86799,
                                                       'max_points': 8.19,
                                                       'expected_weighted_points': 7.1088381,
                                                       'thresholds': {'low': 0.0,
                                                                      'medium': 300.0,
                                                                      'high': 500.0,
                                                                      'ultra': {'rule': 'best_max',
                                                                                'source_formula': '=MAX(K23:O23)'}},
                                                       'dynamic_ultra_threshold': 435.98},
                                                      {'environment': 'DriveCity',
                                                       'kpi_code': 'C30',
                                                       'kpi': 'FDTT UL THROUGHPUT P90 [Mbit/s]',
                                                       'operator': 'O2 (UK)',
                                                       'measured_value': 81.405,
                                                       'score_range_label': 'medium',
                                                       'expected_score_fraction': 0.8628100000000001,
                                                       'max_points': 7.6049999999999995,
                                                       'expected_weighted_points': 6.56167005,
                                                       'thresholds': {'low': 0.0,
                                                                      'medium': 50.0,
                                                                      'high': 100.0,
                                                                      'ultra': {'rule': 'best_max',
                                                                                'source_formula': '=MAX(M28:O28)'}},
                                                       'dynamic_ultra_threshold': 109.669},
                                                      {'environment': 'DriveConnectionroad',
                                                       'kpi_code': 'C30',
                                                       'kpi': 'FDTT UL THROUGHPUT P90 [Mbit/s]',
                                                       'operator': '3',
                                                       'measured_value': 103.32,
                                                       'score_range_label': 'max',
                                                       'expected_score_fraction': 1.0,
                                                       'max_points': 4.095,
                                                       'expected_weighted_points': 4.095,
                                                       'thresholds': {'low': 0.0,
                                                                      'medium': 50.0,
                                                                      'high': 100.0,
                                                                      'ultra': {'rule': 'best_max',
                                                                                'source_formula': '=MAX(K28:O28)'}},
                                                       'dynamic_ultra_threshold': 103.32},
                                                      {'environment': 'DriveCity',
                                                       'kpi_code': 'C31',
                                                       'kpi': 'BROWSING TIME TO 1MB [ms]',
                                                       'operator': 'EE',
                                                       'measured_value': 872.918211277,
                                                       'score_range_label': 'max',
                                                       'expected_score_fraction': 1,
                                                       'max_points': 33.800000000000004,
                                                       'expected_weighted_points': 33.800000000000004,
                                                       'thresholds': {'low': 3000.0,
                                                                      'medium': 2500.0,
                                                                      'high': 1800.0,
                                                                      'ultra': {'rule': 'best_min',
                                                                                'source_formula': '=MIN(M29:O29)'}},
                                                       'dynamic_ultra_threshold': 1038.925624792},
                                                      {'environment': 'DriveCity',
                                                       'kpi_code': 'C11',
                                                       'kpi': 'CALL SUCCESS RATIO [%]',
                                                       'operator': 'O2 (UK)',
                                                       'measured_value': 99.663946231,
                                                       'score_range_label': 'medium',
                                                       'expected_score_fraction': 0.9663946230999997,
                                                       'max_points': 56.875,
                                                       'expected_weighted_points': 54.96369418881248,
                                                       'thresholds': {'low': 85.0,
                                                                      'medium': 98.0,
                                                                      'high': 100.0,
                                                                      'ultra': None},
                                                       'dynamic_ultra_threshold': None},
                                                      {'environment': 'DriveCity',
                                                       'kpi_code': 'C36',
                                                       'kpi': 'INTERACTIVITY PACKET ERROR RATIO '
                                                              '[%]',
                                                       'operator': 'O2 (UK)',
                                                       'measured_value': 6.466648178,
                                                       'score_range_label': 'low',
                                                       'expected_score_fraction': 0.5653362915200001,
                                                       'max_points': 5.07,
                                                       'expected_weighted_points': 2.8662549980064007,
                                                       'thresholds': {'low': 10.0,
                                                                      'medium': 5.0,
                                                                      'high': 1.0,
                                                                      'ultra': None},
                                                       'dynamic_ultra_threshold': None},
                                                      {'environment': 'DriveConnectionroad',
                                                       'kpi_code': 'C37',
                                                       'kpi': 'INTERACTIVITY MEDIAN RTT [MS]',
                                                       'operator': 'O2 (UK)',
                                                       'measured_value': 43.86,
                                                       'score_range_label': 'medium',
                                                       'expected_score_fraction': 0.8114,
                                                       'max_points': 10.92,
                                                       'expected_weighted_points': 8.860488,
                                                       'thresholds': {'low': 60.0,
                                                                      'medium': 45.0,
                                                                      'high': 25.0,
                                                                      'ultra': None},
                                                       'dynamic_ultra_threshold': None},
                                                      {'environment': 'DriveCity',
                                                       'kpi_code': 'C15',
                                                       'kpi': 'MULTI RAB DATA TRANSFER SUCCESS '
                                                              'RATIO [%]',
                                                       'operator': 'EE',
                                                       'measured_value': 100,
                                                       'score_range_label': 'max',
                                                       'expected_score_fraction': 1,
                                                       'max_points': 9.1,
                                                       'expected_weighted_points': 9.1,
                                                       'thresholds': {'low': 80.0,
                                                                      'medium': 98.5,
                                                                      'high': 100.0,
                                                                      'ultra': None},
                                                       'dynamic_ultra_threshold': None}]}}


def scoring_configuration() -> dict:
    """Return an independent, validated scoring seed fixture for tests."""
    configuration = deepcopy(_INITIAL_SCORING_CONFIGURATION)
    legacy_codes = [metric['code'] for metric in configuration['metrics']]
    code_map = {code: f'K{index}' for index, code in enumerate(legacy_codes, start=1)}
    for metric in configuration['metrics']:
        metric['code'] = code_map[metric['code']]
        for context in metric['contexts'].values():
            ultra = context['thresholds'].get('ultra')
            if isinstance(ultra, dict) and ultra.get('rule') == 'fixed':
                context['thresholds']['ultra'] = ultra['value']
    configuration['scope']['environments']['Walk'] = {
        'sheet': 'Walk', 'g_level_1': 'Walk',
    }
    configuration['scope']['environment_mapping']['Walk'] = 'Walk'
    for metric in configuration['metrics']:
        walk = deepcopy(metric['contexts']['DriveCity'])
        walk['max_points'] = 0
        walk.pop('weight_share', None)
        metric['contexts']['Walk'] = walk
    configuration['gap_priority'] = [code_map.get(code, code) for code in configuration.get('gap_priority', legacy_codes)]
    examples = configuration.get('validation_examples', {})
    samples = [examples.get('mapping_workbook_sample'), *examples.get('mapping_workbook_samples', [])]
    for sample in filter(None, samples):
        if isinstance(sample.get('kpi_code'), str):
            sample['kpi_code'] = code_map.get(sample['kpi_code'], sample['kpi_code'])
        if 'thresholds' not in sample:
            continue
        ultra = sample['thresholds'].get('ultra')
        if isinstance(ultra, dict) and ultra.get('rule') == 'fixed':
            sample['thresholds']['ultra'] = ultra['value']
    return validate_scoring_configuration(configuration)


def legacy_scoring_configuration() -> dict:
    """Return the original C-coded two-environment configuration for migration tests."""
    return deepcopy(_INITIAL_SCORING_CONFIGURATION)


def load_initial_scoring_configuration() -> dict:
    """Return the self-contained initial-methodology fixture without file I/O."""
    configuration = scoring_configuration()
    examples = deepcopy(_INITIAL_SCORING_CONFIGURATION.get('validation_examples', {}))
    legacy_codes = [metric['code'] for metric in _INITIAL_SCORING_CONFIGURATION['metrics']]
    code_map = {code: f'K{index}' for index, code in enumerate(legacy_codes, start=1)}
    samples = [examples.get('mapping_workbook_sample'), *examples.get('mapping_workbook_samples', [])]
    for sample in filter(None, samples):
        if isinstance(sample.get('kpi_code'), str):
            sample['kpi_code'] = code_map.get(sample['kpi_code'], sample['kpi_code'])
        ultra = sample.get('thresholds', {}).get('ultra')
        if isinstance(ultra, dict) and ultra.get('rule') == 'fixed':
            sample['thresholds']['ultra'] = ultra['value']
    configuration['validation_examples'] = examples
    return configuration
