services:
  app-dev:
    build:
      context: ..
      dockerfile: docker/dockerfile
    container_name: ${CONTAINER_NAME}-dev
    env_file:
      - .env
    ports:
      - "${APP_DEV_PORT}:7278"
    volumes:
      - ../src:/app/src
      - ${HOST_CONFIG_DIR}:/app/config
      - ${HOST_DATA_DIR}:/app/data
    command: uvicorn src.DashboardAnalytic:app --host 0.0.0.0 --port 7278 --reload --reload-dir /app/src
    restart: unless-stopped
